apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soprano.fullname" . }}-configmap
  labels:
    {{- include "soprano.labels" . | nindent 4 }}
data:
  queries.yaml: |
    queries:
      {{- range $key, $value := $.Values.queries }}
        {{ $key }}: {{ $value }}
      {{- end }}