{
 "title": "EKS Audit Log Dashboard Copy",
 "description": "EKS Audit Log Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "exec-attemptions-summary-daily",
   "type": "stat",
   "description": "This panel shows up the daily exec attemption metrics",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(eks_audit_metric{job=\"soprano\", audit_metric_type=\"exec-attemptions\"}[24h])"
    }
   ]
  },
  {
   "title": "non-authorized-access-daily",
   "type": "stat",
   "description": "This panel shows up the daily exec attemption metrics",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(eks_audit_metric{job=\"soprano\", audit_metric_type=\"four-zero-three-results\"}[24h])"
    }
   ]
  },
  {
   "title": "forbidden-decisions-daily",
   "type": "stat",
   "description": "This panel shows up the daily forbidden access count",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(eks_audit_metric{job=\"soprano\", audit_metric_type=\"forbidden-decisions\"}[24h])"
    }
   ]
  },
  {
   "title": "exec-attemptions",
   "type": "timeseries",
   "description": "That panel is responsible to shows up exec attemptions to the cluster",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "eks_audit_metric{job=\"soprano\", audit_metric_type=\"exec-attemptions\"}"
    }
   ]
  },
  {
   "title": "non-authorized-access",
   "type": "timeseries",
   "description": "This panels shows the forbidden access through to the cluster",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "eks_audit_metric{job=\"soprano\", audit_metric_type=\"four-zero-three-results\"}"
    }
   ]
  },
  {
   "title": "forbidden-decisions",
   "type": "timeseries",
   "description": "That panel shows the metrics that is decided as a forbidden by the API Server",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "eks_audit_metric{job=\"soprano\", audit_metric_type=\"forbidden-decisions\"}"
    }
   ]
  }
 ]
}